### ISSUE TITLE
Can't retrieve Add-ons package list

### ISSUE THREAD

**Issue by sthry** [biolab/orange3#4834]
I want to add new Add-ons on Orange, but i got warning:

![image](https://user-images.githubusercontent.com/44202888/83345129-b72f1180-a339-11ea-8844-55de4433e1b8.png)

I tried to reinstall Orange, the Add-ons list appear everytime i fresh install orange,
but after i'm done adding 1 or 2 Add-ons and tried to add another one, the warning appear again,

Complete log
Traceback (most recent call last):
  File "C:\Users\Soy\AppData\Local\Orange\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Soy\AppData\Local\Orange\lib\site-packages\orangecanvas\application\addons.py", line 679, in <lambda>
    lambda config=config: (config, list_available_versions(config)),
  File "C:\Users\Soy\AppData\Local\Orange\lib\site-packages\orangecanvas\application\addons.py", line 1227, in list_available_versions
    response = session.get(PYPI_API_JSON.format(name=p))
  File "C:\Users\Soy\AppData\Local\Orange\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Soy\AppData\Local\Orange\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Soy\AppData\Local\Orange\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Soy\AppData\Local\Orange\lib\site-packages\cachecontrol\adapter.py", line 44, in send
    cached_response = self.controller.cached_request(request)
  File "C:\Users\Soy\AppData\Local\Orange\lib\site-packages\cachecontrol\controller.py", line 145, in cached_request
    resp = self.serializer.loads(request, cache_data)
  File "C:\Users\Soy\AppData\Local\Orange\lib\site-packages\cachecontrol\serialize.py", line 97, in loads
    return getattr(self, "_loads_v{}".format(ver))(request, data)
  File "C:\Users\Soy\AppData\Local\Orange\lib\site-packages\cachecontrol\serialize.py", line 182, in _loads_v4
    cached = msgpack.loads(data, encoding="utf-8")
  File "msgpack/_unpacker.pyx", line 144, in msgpack._cmsgpack.unpackb
TypeError: unpackb() got an unexpected keyword argument 'encoding'

**Orange version:**
Orange 3.25.1

**Expected behavior**
Add new Add-ons to Orange

**Operating system:**
Windows 10

**Comment by chasbecker** [comment]
I've had the same problem.

**Comment by ales-erjavec** [comment]
Can you open Orange Command Prompt and run

```batch
conda install -c conda-forge cachecontrol=0.12.6
```

**Comment by chasbecker** [comment]
Late at night here, I will try in the morning.  Thank you.

**Comment by sthry** [comment]
> Can you open Orange Command Prompt and run
> 
> ```batchfile
> conda install -c conda-forge cachecontrol=0.12.6
> ```

Thank you, its work for me. 👍

**Comment by chasbecker** [comment]
That did work.  I think my problem is on the PostgreSQL side.  This Orange 3 environment is very impressive.  Many years ago I worked in Delphi (1.0) and Orange reminds me of that experience.  Thank you for this product and for your assistance!
________________________________

**Comment by chasbecker** [comment]
Thank you!

**Comment by janezd** [comment]
Duplicate of #4720.
