### ISSUE TITLE
SQL Widget Doesn't Work With MSSQL on Python 3.6

### ISSUE THREAD

**Issue by nikicc** [biolab/orange3#2754]
##### Orange version

3.6.0

##### Expected behavior
One can use SQL widget with MSSQL database on Python 3.6 on Windows.

##### Actual behavior
MSSQL driver (`pymssql`) wheels are missing for Python 3.6. The problem occurs with the standalone installer since Miniconda 32bit installer uses Python 3.6 by default.

##### Steps to reproduce the behavior
Install Orange on Windows with Miniconda 32bit installer. Try to install `pymssql`.

##### Additional info (worksheets, data, screenshots, ...)
@astaric already prepared the 32bit installer with Python 3.5: https://orange.biolab.si/download/files/Orange3-3.6.0-Python35-Miniconda-x86.exe

**Comment by abitofalchemy** [comment]
Does `pymssql` require installation using `sudo`?  When I try installing I get this error: 
`_mssql.c:266:10: fatal error: 'sqlfront.h' file not found`

I get this from: 
```
$ pip install -r requirements-sql.txtpython
  _mssql.c:266:10: fatal error: 'sqlfront.h' file not found
  #include "sqlfront.h"
           ^~~~~~~~~~~~
  1 error generated.
  error: command 'clang' failed with exit status 1

  ----------------------------------------
  Failed building wheel for pymssql
```

**Comment by kernc** [comment]
```text
% apt-file find sqlfront.h                                                                                                                                                                                                                                                                           
freetds-dev: /usr/include/sqlfront.h
```
It [requires FreeDTS](http://pymssql.org/en/stable/freetds.html). On Debian-based systems in freedts-dev package.

**Comment by robertcv** [comment]
For macos install FreeTDS with: 
```
brew install freetds
```
If the `fatal error: 'sqlfront.h' file not found` persists install pymssql from git:
```
pip install Cython
pip install git+https://github.com/pymssql/pymssql.git
```

**Comment by ajdapretnar** [comment]
This I think could go into [Wiki](https://github.com/biolab/orange3/wiki/Installation-of-PostgreSQL-extensions).

**Comment by ajdapretnar** [comment]
@robertcv @astaric  I just threw in what we had here on Wiki. You can check to see I did not write stupid things (or perhaps add/improve it).
